### ISSUE TITLE
DI compilation failing

### ISSUE THREAD

**Issue by tr33m4n** [apexxpayment/base#1]
Hi there,

DI compilation is failing due to the requirement of the "Signifyd" module here https://github.com/apexxpayment/base/blob/master/Model/Payment/MappingPayment/ExpYearMapper.php#L5 on Magento 2.3.6 EE.

```
PHP Fatal error:  Uncaught Error: Class 'Signifyd\Connect\Model\Payment\Base\ExpYearMapper' not found in /vendor/apexxpayment/base/Model/Payment/MappingPayment/ExpYearMapper.php:7
Stack trace:
#0 /vendor/composer/ClassLoader.php(444): include()
#1 /vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/travis/bu...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Apexx\\Base\\Mode...')
#3 [internal function]: spl_autoload_call('Apexx\\Base\\Mode...')
#4 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(133): class_exists('Apexx\\Base\\Mode...')
#5 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses(Array, '/home/travis/bu...')
#6 /setup/src/Magento/Setup/Module/Di/Code/Reader in /vendor/apexxpayment/base/Model/Payment/MappingPayment/ExpYearMapper.php on line 7
```
Perhaps using plugins would be a better approach as they'd gracefully fail if the class did not exist

**Comment by tr33m4n** [comment]
Never mind, it was an issue with our install! Sorry about that
